-- S&S Gym Egyptian foods seed
-- Run after supabase/migrations/001_initial_schema.sql.
-- These macros are user-provided approximate values, not medical-grade nutrition data.

insert into public.food_items (
  food_name,
  serving_size,
  calories,
  protein_g,
  carbs_g,
  fat_g,
  category,
  cuisine,
  tags,
  notes,
  source_type,
  is_global,
  is_editable_by_user
) values
('Molokhia','1 bowl',180,5.0,12.0,12.0,'Stew','Egyptian',array['egyptian','stew'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('White rice','1 cup cooked',260,5.0,52.0,4.0,'Carb','Egyptian',array['rice'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Rice with vermicelli','1 cup',300,6.0,55.0,7.0,'Carb','Egyptian',array['rice'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Baladi bread','1 medium loaf',300,9.0,60.0,2.0,'Bread','Egyptian',array['bread'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Half baladi bread','1/2 loaf',150,4.5,30.0,1.0,'Bread','Egyptian',array['bread'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Quarter baladi bread','1/4 loaf',75,2.0,15.0,0.5,'Bread','Egyptian',array['bread'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Boiled egg','1 egg',75,6.0,1.0,5.0,'Protein','Egyptian',array['egg'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Fried egg','1 egg',110,6.0,1.0,8.0,'Protein','Egyptian',array['egg'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Omelette','2 eggs',220,13.0,2.0,17.0,'Protein','Egyptian',array['egg'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Shakshuka','1 plate',320,18.0,15.0,22.0,'Breakfast','Egyptian',array['egg','tomato'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Ful medames','1 cup',280,17.0,45.0,4.0,'Legumes','Egyptian',array['beans'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Ful with oil','1 cup + oil',380,17.0,45.0,15.0,'Legumes','Egyptian',array['beans'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Ful sandwich','1 sandwich',430,18.0,70.0,8.0,'Sandwich','Egyptian',array['beans','bread'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Taameya / falafel','1 piece',90,3.0,8.0,5.0,'Legumes','Egyptian',array['falafel'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Taameya sandwich','1 sandwich',500,16.0,65.0,20.0,'Sandwich','Egyptian',array['falafel','bread'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Besara','1 bowl',320,20.0,42.0,9.0,'Legumes','Egyptian',array['beans'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Lentil soup','1 bowl',280,15.0,40.0,7.0,'Soup','Egyptian',array['lentils'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Black lentils / ads be gebba','1 cup',300,18.0,45.0,6.0,'Legumes','Egyptian',array['lentils'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Koshary','1 medium bowl',750,22.0,120.0,20.0,'Meal','Egyptian',array['koshary','rice','pasta'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Koshary small','1 small bowl',500,15.0,85.0,13.0,'Meal','Egyptian',array['koshary','rice','pasta'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Red pasta sauce','1/2 cup',90,2.0,12.0,4.0,'Sauce','Egyptian',array['pasta'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Pasta with red sauce','1 plate',500,14.0,85.0,12.0,'Meal','Egyptian',array['pasta'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Plain pasta','1 cup cooked',220,8.0,43.0,1.0,'Carb','Egyptian',array['pasta'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Macarona bechamel','1 slice',650,28.0,55.0,35.0,'Meal','Egyptian',array['pasta','bechamel'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Bechamel sauce','1/2 cup',180,5.0,15.0,11.0,'Sauce','Egyptian',array['bechamel'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Egyptian potato stew','1 bowl',300,6.0,42.0,12.0,'Stew','Egyptian',array['potato'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Fried potatoes','1 plate',450,6.0,55.0,22.0,'Side','Egyptian',array['potato'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Air-fryer potatoes','1 plate',250,5.0,45.0,5.0,'Side','Egyptian',array['potato'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Potato sandwich','1 sandwich',520,10.0,65.0,22.0,'Sandwich','Egyptian',array['potato','bread'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Mashed potatoes','1 plate',320,6.0,45.0,12.0,'Side','Egyptian',array['potato'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Mahshi rice filling','1 cup',330,6.0,55.0,10.0,'Meal','Egyptian',array['mahshi','rice'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Mahshi warak enab','10 pieces',420,8.0,65.0,14.0,'Meal','Egyptian',array['mahshi'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Mahshi kousa','4 pieces',380,10.0,55.0,13.0,'Meal','Egyptian',array['mahshi'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Mahshi kromb','6 rolls',430,11.0,62.0,15.0,'Meal','Egyptian',array['mahshi'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Mahshi eggplant','4 pieces',400,9.0,55.0,15.0,'Meal','Egyptian',array['mahshi'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Roasted eggplant','1 medium',120,3.0,25.0,1.0,'Vegetable','Egyptian',array['eggplant'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Fried eggplant','1 plate',350,5.0,25.0,25.0,'Vegetable','Egyptian',array['eggplant'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Baba ghanoush','1/2 cup',130,3.0,10.0,9.0,'Dip','Egyptian',array['eggplant'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Tehina salad','1/4 cup',180,5.0,6.0,16.0,'Dip','Egyptian',array['tehina'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Egyptian salad','1 bowl',80,3.0,14.0,2.0,'Salad','Egyptian',array['salad'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Pickles','1 small plate',30,1.0,6.0,0.0,'Side','Egyptian',array['pickles'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Cucumber yogurt salad','1 bowl',120,6.0,10.0,6.0,'Salad','Egyptian',array['yogurt'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Moussaka Egyptian style','1 plate',430,14.0,25.0,30.0,'Meal','Egyptian',array['eggplant'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Bamya','1 bowl',220,6.0,22.0,12.0,'Stew','Egyptian',array['okra'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Peas and carrots stew','1 bowl',260,8.0,35.0,10.0,'Stew','Egyptian',array['vegetables'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('White beans stew','1 bowl',330,15.0,45.0,9.0,'Stew','Egyptian',array['beans'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Green beans stew','1 bowl',220,7.0,25.0,10.0,'Stew','Egyptian',array['beans'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Torly vegetables','1 plate',250,7.0,30.0,11.0,'Vegetable','Egyptian',array['vegetables'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Spinach stew','1 bowl',210,8.0,20.0,10.0,'Stew','Egyptian',array['spinach'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Zucchini stew','1 bowl',190,5.0,18.0,11.0,'Stew','Egyptian',array['zucchini'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Grilled chicken breast','150 g',250,45.0,0.0,6.0,'Protein','Egyptian',array['chicken'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Grilled chicken thigh','1 piece',280,28.0,0.0,18.0,'Protein','Egyptian',array['chicken'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Boiled chicken breast','150 g',240,45.0,0.0,5.0,'Protein','Egyptian',array['chicken'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Roasted chicken quarter','1 quarter',380,42.0,0.0,22.0,'Protein','Egyptian',array['chicken'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Chicken pane','1 piece',450,35.0,25.0,24.0,'Protein','Egyptian',array['chicken'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Chicken shawarma meat','150 g',360,38.0,5.0,20.0,'Protein','Egyptian',array['chicken','shawarma'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Chicken kofta','150 g',320,32.0,8.0,18.0,'Protein','Egyptian',array['chicken','kofta'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Grilled beef kofta','150 g',400,30.0,5.0,28.0,'Protein','Egyptian',array['beef','kofta'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Beef kebab','150 g',380,36.0,2.0,25.0,'Protein','Egyptian',array['beef'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Beef cubes / kabab halla','150 g',360,34.0,5.0,24.0,'Protein','Egyptian',array['beef'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Minced beef cooked','150 g',375,32.0,0.0,27.0,'Protein','Egyptian',array['beef'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Beef shawarma meat','150 g',420,32.0,5.0,30.0,'Protein','Egyptian',array['beef','shawarma'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Alexandrian liver','150 g',360,30.0,10.0,22.0,'Protein','Egyptian',array['liver'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Sogo'' baladi','150 g',420,21.0,7.0,35.0,'Protein','Egyptian',array['sausage'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Hawawshi','1 piece',650,32.0,55.0,32.0,'Meal','Egyptian',array['beef','bread'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Burger patty Egyptian style','150 g',390,28.0,6.0,28.0,'Protein','Egyptian',array['beef'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Grilled fish','1 medium fish',350,45.0,0.0,18.0,'Protein','Egyptian',array['fish'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Fried fish','1 medium fish',520,42.0,20.0,30.0,'Protein','Egyptian',array['fish'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Tuna','1 can drained',180,30.0,0.0,6.0,'Protein','Egyptian',array['fish'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Tuna sandwich','1 sandwich',420,28.0,45.0,14.0,'Sandwich','Egyptian',array['fish','bread'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Shrimp grilled','150 g',180,35.0,2.0,3.0,'Protein','Egyptian',array['seafood'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Fried shrimp','150 g',380,30.0,25.0,18.0,'Protein','Egyptian',array['seafood'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Sayadeya rice','1 cup',350,7.0,60.0,10.0,'Rice','Egyptian',array['rice','fish'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Fatta rice','1 cup',330,6.0,55.0,9.0,'Rice','Egyptian',array['rice','fatta'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Crispy bread for fatta','1 cup',220,6.0,40.0,5.0,'Bread','Egyptian',array['fatta','bread'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Garlic vinegar sauce','1/4 cup',70,1.0,8.0,4.0,'Sauce','Egyptian',array['fatta','sauce'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Roz me''ammar','1 portion',520,12.0,65.0,24.0,'Rice','Egyptian',array['rice'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Feteer meshaltet','1 medium piece',700,12.0,75.0,38.0,'Pastry','Egyptian',array['feteer'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Feteer with cheese','1 portion',850,25.0,80.0,48.0,'Pastry','Egyptian',array['feteer','cheese'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Feteer with honey','1 portion',780,12.0,105.0,34.0,'Pastry','Egyptian',array['feteer','sweet'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Sambosa cheese','1 piece',100,3.0,9.0,6.0,'Snack','Egyptian',array['cheese'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Sambosa meat','1 piece',120,5.0,9.0,7.0,'Snack','Egyptian',array['meat'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Roumy cheese','50 g',180,12.0,1.0,14.0,'Dairy','Egyptian',array['cheese'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('White cheese / gebna beda','50 g',130,8.0,2.0,10.0,'Dairy','Egyptian',array['cheese'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Cottage cheese / areesh','100 g',110,18.0,4.0,2.0,'Dairy','Egyptian',array['cheese'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Cheese tomato sandwich','1 sandwich',380,15.0,45.0,16.0,'Sandwich','Egyptian',array['cheese','bread'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Roumy cheese sandwich','1 sandwich',480,20.0,45.0,24.0,'Sandwich','Egyptian',array['cheese','bread'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Yogurt small cup','1 cup',100,6.0,10.0,4.0,'Dairy','Egyptian',array['yogurt'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Greek yogurt','1 cup',150,20.0,8.0,4.0,'Dairy','Egyptian',array['yogurt'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Milk','1 cup',120,8.0,12.0,5.0,'Drink','Egyptian',array['milk'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Tea with milk','1 cup',80,4.0,8.0,3.0,'Drink','Egyptian',array['tea','milk'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Nescafe with milk','1 cup',90,5.0,10.0,3.0,'Drink','Egyptian',array['coffee','milk'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Sugar cane juice','1 cup',180,0.0,45.0,0.0,'Drink','Egyptian',array['juice'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Hibiscus / karkade sweetened','1 cup',120,0.0,30.0,0.0,'Drink','Egyptian',array['karkade'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Sahlab','1 cup',280,8.0,45.0,8.0,'Drink','Egyptian',array['sweet'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Roz bel laban','1 bowl',350,9.0,55.0,10.0,'Dessert','Egyptian',array['rice','sweet'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Om Ali','1 bowl',600,12.0,65.0,34.0,'Dessert','Egyptian',array['sweet'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Basbousa','1 piece',300,5.0,45.0,12.0,'Dessert','Egyptian',array['sweet'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Konafa','1 piece',420,6.0,55.0,22.0,'Dessert','Egyptian',array['sweet'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false),
('Zalabya / loqmet el qady','5 pieces',350,4.0,55.0,14.0,'Dessert','Egyptian',array['sweet'],'Nutrition values are approximate and may vary depending on preparation and portion size.','user_provided_approximate_macro_table',true,false);
